# This is a basic workflow to help you get started with Actions
name: deployment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CI: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages 📦
        run: yarn
      - name: Deploy to GH Pages 🎨
        run: |
          git config --global user.email ${{secrets.SECRET_EMAIL}}
          git config --global user.name "samiurprapon"
          git remote set-url origin https://${{secrets.ACCESS_TOKEN}}@github.com/samiurprapon/blog.git

          CI=false yarn run deploy
